const { chromium } = require(process.env.PLAYWRIGHT_PATH || 'playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const base = process.env.PREVIEW_URL || 'http://127.0.0.1:4178';
const output = path.resolve(__dirname, '../.qa');

(async () => {
  const browser = await chromium.launch();
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(base);
  assert.equal(await page.locator('html').getAttribute('data-scroll-mode'), 'smooth');
  assert.equal(await page.evaluate(() => getComputedStyle(document.documentElement).scrollBehavior), 'auto');
  await page.mouse.move(720,400);
  await page.mouse.wheel(0,600);
  await page.waitForTimeout(70);
  const early = await page.evaluate(() => scrollY);
  await page.waitForTimeout(1000);
  const settled = await page.evaluate(() => scrollY);
  assert(early > 0 && early < 599, `Expected interpolation, saw ${early}`);
  assert(Math.abs(settled - 600) < 3, `1:1 wheel distance, saw ${settled}`);
  await page.mouse.wheel(0,-600);
  await page.waitForTimeout(1100);
  assert(await page.evaluate(() => scrollY) < 3);
  await page.locator('.site-nav a[href="#about"]').click();
  await page.waitForTimeout(1400);
  assert.equal(new URL(page.url()).hash, '#about');
  const aboutTop = await page.locator('#about').evaluate(el => el.getBoundingClientRect().top);
  assert(Math.abs(aboutTop - 76) < 4, `About anchor should clear header: ${aboutTop}`);
  assert.equal(await page.locator('#about').evaluate(el => document.activeElement === el), true);
  const firstParallax = await page.locator('.about-visual img').evaluate(el => el.style.translate);
  await page.screenshot({ path: path.join(output,'smooth-about.png') });
  await page.mouse.move(800,400);
  await page.mouse.wheel(0,300);
  await page.waitForTimeout(1000);
  assert.notEqual(await page.locator('.about-visual img').evaluate(el => el.style.translate), firstParallax);
  await page.keyboard.press('PageDown');
  await page.waitForTimeout(600);
  assert(await page.evaluate(() => scrollY) > settled + 600, 'Keyboard paging remains available');
  await page.locator('.site-nav a[href="#contact"]').click();
  await page.waitForTimeout(1500);
  assert.equal(new URL(page.url()).hash, '#contact');
  const contactPosition = await page.evaluate(() => ({ y: scrollY, height: document.documentElement.scrollHeight, top: document.querySelector('#contact').getBoundingClientRect().top, atEnd: scrollY + innerHeight >= document.documentElement.scrollHeight - 3 }));
  assert(contactPosition.top >= 64 && (Math.abs(contactPosition.top - 76) < 5 || contactPosition.atEnd), 'Contact clears header or stops at the document end: ' + JSON.stringify(contactPosition));
  await page.locator('textarea').fill(Array(35).fill('QA nested scrolling line.').join('\n'));
  await page.locator('textarea').hover();
  const outerBefore = await page.evaluate(() => scrollY);
  await page.mouse.wheel(0,160);
  await page.waitForTimeout(300);
  assert(await page.locator('textarea').evaluate(el => el.scrollTop) > 0);
  assert(Math.abs(await page.evaluate(() => scrollY) - outerBefore) < 2, 'Text area scroll stays native');
  await page.goBack();
  await page.waitForTimeout(700);
  assert.equal(new URL(page.url()).hash, '#about');
  await page.reload();
  await page.waitForTimeout(500);
  assert.equal(new URL(page.url()).hash, '#about');
  assert(await page.evaluate(() => scrollY) > 1000, 'Midpage refresh remains midpage');
  await page.locator('[data-motion-toggle]').click();
  assert.equal(await page.locator('html').getAttribute('data-scroll-mode'), 'native');
  assert.equal(await page.locator('html').evaluate(el => el.classList.contains('lenis')), false);
  assert.equal(await page.locator('.about-visual img').evaluate(el => el.style.translate), 'none');
  await page.locator('[data-motion-toggle]').click();
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.waitForFunction(() => document.documentElement.dataset.scrollMode === 'native');
  assert.equal(await page.locator('html').evaluate(el => el.classList.contains('lenis')), false);
  await page.emulateMedia({ reducedMotion: 'no-preference' });
  await page.waitForFunction(() => document.documentElement.dataset.scrollMode === 'smooth');

  // A missing enhancement cannot break links or scrolling.
  const fallback = await browser.newPage();
  await fallback.route('**/lenis.min.js', route => route.abort());
  await fallback.goto(base);
  assert.equal(await fallback.locator('html').getAttribute('data-scroll-mode'), 'native');
  await fallback.locator('.site-nav a[href="#pricing"]').click();
  await fallback.waitForTimeout(1200);
  assert.equal(new URL(fallback.url()).hash, '#pricing');
  await fallback.close();
  const phone = await browser.newPage({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true });
  await phone.goto(base);
  assert.equal(await phone.locator('html').getAttribute('data-scroll-mode'), 'native');
  assert.equal(await phone.locator('html').evaluate(el => el.classList.contains('lenis')), false);
  await phone.close();
  assert.deepEqual(errors, []);
  const report = { passed: true, earlyWheelPosition: early, settledWheelPosition: settled, pageErrors: errors, checks: ['real wheel interpolation and 1:1 distance', 'reverse wheel', 'hash and focus', 'header offset', 'about parallax', 'keyboard PageDown', 'native textarea scrolling', 'back and midpage refresh', 'pause and reduced motion destroy smoother', 'missing library fallback', 'native touch configuration'], limitation: 'Chromium emulation; physical wheel, trackpad and phone feel not measured.' };
  fs.writeFileSync(path.join(output,'scroll-report.json'), JSON.stringify(report,null,2));
  console.log(JSON.stringify(report));
  await browser.close();
})().catch(error => { console.error(error); process.exit(1); });
